# This is the default configuration file for morfo.

# The compiler to use
cc = "gcc"

# The flags to pass to the compiler on every invocation
cflags = ["-g"]

# The folder to put the compiled files in
builddir = ".out"
