version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run: |
          cargo --version
          cargo test
  lint:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run: |
          cargo --version
          cargo fmt --all -- --check
          cargo clippy
  publish:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run: |
          cargo publish --token $CRATES_TOKEN

workflows:
  main:
    jobs:
      - test
      - lint
  release:
    jobs:
      - test:
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - lint:
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - test
            - lint
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
