version: 2.1

orbs:
  gh: circleci/github-cli@2.3.0
jobs:
  test:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run: |
          cargo --version
          cargo test
  lint:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run: |
          cargo --version
          cargo fmt --all -- --check
          cargo clippy
  publish:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run: |
          cargo --version
          cargo publish --token $CRATES_TOKEN
  check_version:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: ./check_version.sh
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - gh/setup
      - run: gh release create $TAG -t $VERSION
      - gh/clone
    

workflows:
  main:
    jobs:
      - test
      - lint
      - check_version:
          filters:
            branches:
              ignore: main
  release:
    jobs:
      - test:
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - lint:
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - test
            - lint
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - test
            - lint
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
